import pandas as pd
from pathlib import Path


# ============================================================
# PROJECT PATHS
# ============================================================

ROOT_DIR = Path(__file__).resolve().parents[1]

IDS_RESULTS_FILE = ROOT_DIR / "data" / "ids_results.csv"


# ============================================================
# LOAD IDS RESULTS
# ============================================================

def load_ids_results():
    """
    Load the final IDS results generated by ids_engine.py.
    """

    assert IDS_RESULTS_FILE.exists(), (
        f"IDS results file not found: {IDS_RESULTS_FILE}"
    )

    df = pd.read_csv(IDS_RESULTS_FILE)

    assert not df.empty, "IDS results file is empty."

    return df


# ============================================================
# TEST 1
# ============================================================

def test_ids_results_load():
    """
    Verify that the final IDS results file can be loaded.
    """

    df = load_ids_results()

    assert isinstance(df, pd.DataFrame)
    assert len(df) > 0


# ============================================================
# TEST 2
# ============================================================

def test_required_ids_columns_exist():
    """
    Verify that all important IDS columns exist.
    """

    df = load_ids_results()

    required_columns = {
        "ids_classification",
        "ids_severity",
        "ids_risk_score",
        "ids_detection_method",
        "ids_reason",
        "ml_classification",
        "ml_risk_score",
        "ml_severity",
    }

    missing_columns = required_columns - set(df.columns)

    assert not missing_columns, (
        f"Missing required IDS columns: {missing_columns}"
    )


# ============================================================
# TEST 3
# ============================================================

def test_ids_classification_values():
    """
    Verify that IDS classifications contain recognized values.
    """

    df = load_ids_results()

    allowed_values = {
        "NORMAL",
        "SUSPICIOUS",
        "POTENTIAL INTRUSION",
    }

    actual_values = set(
        df["ids_classification"]
        .dropna()
        .astype(str)
        .unique()
    )

    unexpected_values = actual_values - allowed_values

    assert not unexpected_values, (
        f"Unexpected IDS classifications: {unexpected_values}"
    )


# ============================================================
# TEST 4
# ============================================================

def test_ids_severity_values():
    """
    Verify that IDS severity values are valid.
    """

    df = load_ids_results()

    allowed_values = {
        "INFO",
        "LOW",
        "MEDIUM",
        "HIGH",
        "CRITICAL",
    }

    actual_values = set(
        df["ids_severity"]
        .dropna()
        .astype(str)
        .unique()
    )

    unexpected_values = actual_values - allowed_values

    assert not unexpected_values, (
        f"Unexpected IDS severity values: {unexpected_values}"
    )


# ============================================================
# TEST 5
# ============================================================

def test_ids_risk_scores():
    """
    Verify that IDS risk scores are between 0 and 100.
    """

    df = load_ids_results()

    risk_scores = pd.to_numeric(
        df["ids_risk_score"],
        errors="coerce"
    )

    assert risk_scores.notna().all(), (
        "IDS risk scores contain non-numeric values."
    )

    assert (risk_scores >= 0).all(), (
        "IDS risk score contains values below 0."
    )

    assert (risk_scores <= 100).all(), (
        "IDS risk score contains values above 100."
    )


# ============================================================
# TEST 6
# ============================================================

def test_ml_risk_scores():
    """
    Verify that ML risk scores are between 0 and 100.
    """

    df = load_ids_results()

    ml_risk_scores = pd.to_numeric(
        df["ml_risk_score"],
        errors="coerce"
    )

    assert ml_risk_scores.notna().all(), (
        "ML risk scores contain non-numeric values."
    )

    assert (ml_risk_scores >= 0).all(), (
        "ML risk score contains values below 0."
    )

    assert (ml_risk_scores <= 100).all(), (
        "ML risk score contains values above 100."
    )


# ============================================================
# TEST 7
# ============================================================

def test_detection_methods():
    """
    Verify that IDS detection methods contain only
    recognized detection sources and valid combinations.

    Valid individual detection sources:
        RULE
        ANOMALY
        ML

    Valid examples:
        NONE
        RULE
        ANOMALY
        ML
        RULE + ANOMALY
        RULE + ML
        ANOMALY + ML
        RULE + ANOMALY + ML
    """

    df = load_ids_results()

    actual_methods = set(
        df["ids_detection_method"]
        .dropna()
        .astype(str)
        .str.strip()
        .unique()
    )

    allowed_sources = {
        "RULE",
        "ANOMALY",
        "ML",
    }

    for method in actual_methods:

        # NONE is valid when no detection source triggered.
        if method == "NONE":
            continue

        parts = {
            part.strip()
            for part in method.split("+")
        }

        unexpected_parts = parts - allowed_sources

        assert not unexpected_parts, (
            f"Unexpected detection method '{method}'. "
            f"Unknown detection source(s): {unexpected_parts}"
        )

        assert len(parts) >= 1, (
            f"Invalid empty detection method: '{method}'"
        )

    print("\nActual detection methods:")
    print(df["ids_detection_method"].value_counts())


# ============================================================
# TEST 8
# ============================================================

def test_ml_classification_values():
    """
    Verify that ML classifications contain recognized values.
    """

    df = load_ids_results()

    allowed_values = {
        "NORMAL",
        "SUSPICIOUS",
    }

    actual_values = set(
        df["ml_classification"]
        .dropna()
        .astype(str)
        .unique()
    )

    unexpected_values = actual_values - allowed_values

    assert not unexpected_values, (
        f"Unexpected ML classification values: {unexpected_values}"
    )


# ============================================================
# TEST 9
# ============================================================

def test_ids_result_count():
    """
    Verify that the IDS results contain records.
    """

    df = load_ids_results()

    assert len(df) > 0, (
        "IDS results contain no records."
    )

    print(f"\nIDS result records: {len(df)}")


# ============================================================
# TEST 10
# ============================================================

def test_detection_activity_exists():
    """
    Verify that the final IDS results contain actual
    detection activity.

    Detection activity is determined from the
    ids_detection_method column.

    Examples of valid detection activity:

        ML
        RULE
        ANOMALY
        RULE + ML
        ANOMALY + ML
        RULE + ANOMALY + ML

    NONE is allowed in the dataset, but the complete
    dataset must contain at least one real detection.
    """

    df = load_ids_results()

    # --------------------------------------------------------
    # The final IDS engine records detection activity in
    # ids_detection_method.
    # --------------------------------------------------------

    assert "ids_detection_method" in df.columns, (
        "ids_detection_method column is missing."
    )

    detection_methods = (
        df["ids_detection_method"]
        .dropna()
        .astype(str)
        .str.strip()
        .str.upper()
    )

    assert len(detection_methods) > 0, (
        "No detection methods were recorded."
    )

    # --------------------------------------------------------
    # NONE means no detector triggered for that record.
    # Any other method represents actual detection activity.
    # --------------------------------------------------------

    non_detection_methods = {
        "",
        "NONE",
        "NAN",
        "NULL",
    }

    detected_methods = [
        method
        for method in detection_methods
        if method not in non_detection_methods
    ]

    assert len(detected_methods) > 0, (
        "No detection activity was found in the IDS results."
    )

    print("\nDetection activity found:")
    print(
        pd.Series(detected_methods)
        .value_counts()
    )

    print(
        f"\nRecords with detection activity: "
        f"{len(detected_methods)}"
    )